### ISSUE TITLE
Ignore changes to VM custom data

### ISSUE THREAD

**Issue by stiross79** [equinor/terraform-baseline#121]
### Module Name

vm

### Description

The `custom_data` parameter is only used during the initial deployment of the VM (on the first boot) but it will still force the VM to be replaced if you make any changes to the cloud-init template which you may want to use on new deployments without replacing existing VMs.

```tf
lifecycle {
  ignore_changes = [ 
    custom_data
   ]
}
```

![image](https://github.com/equinor/terraform-azurerm-vm/assets/94676511/e1853ae2-c297-4393-8de3-020c20e93260)

**Comment by stiross79** [comment]
We have multiple environments that create the same VM using the same cloud-init file. From time to time we update this cloud-init file to be applied when we deploy new VMs, but existing VMs should not be recreated. If needed we updated these VMs directly using scripts.

**Comment by hknutsen** [comment]
Couldn't that be considered an edge case though? If the value of `custom_data` is tightly connected to the initial creation of the VM, then it makes sense that changing said value triggers the recreation of the VM.

**Comment by hknutsen** [comment]
Would it be possible to create a variable for the name of the cloud-init config file in your feature module, so that you can use different configs for different VMs without ignoring changes to the `custom_data` argument?

**Comment by stiross79** [comment]
This will not be a very good solution for us and we will probably still need to use our local VM module. I do not see when you ever want to recreate the VM because you made changes to the cloud-init file.

![image](https://github.com/equinor/terraform-baseline/assets/94676511/914b2f20-fc89-4c85-b5ea-4f702363392e)

**Comment by stiross79** [comment]
Would a possible workaround be a boolean variable you can use to ignore custom_data ?

**Comment by hknutsen** [comment]
>  I do not see when you ever want to recreate the VM because you made changes to the cloud-init file. If this is the case I would run terraform apply -replace="azurerm_linux_virtual_machine.this"

I see your point, but I'd still be hesitant to completely ignore changes.

Consider the following scenario where we ignore changes to the `custom_data` argument:

1. You create a VM `vm1` and get the value of `custom_data` from a file `cloud-init.txt`. This config is essential for the VM to do its job.
1. You need to create another VM `vm2` to do a slightly different job, so you update the existing `cloud-init.txt` and then create the VM. Terraform won't make any changes to `vm1` despite the updated config file, since we ignore changes to `custom_data`.
1. You experience a disaster and need to completely rebuild your infrastructure. You re-apply the same Terraform configuration that you used to create `vm1` and `vm2`, however `vm1` is not working as expected as it was not configured using the same cloud-init config as before.

> This will not be a very good solution for us and we will probably still need to use our local VM module.

Would it be possible for you to wrap this module in a local module that handles multiple different cloud-init config files for you?

> Would a possible workaround be a boolean variable you can use to ignore custom_data updates ?

The `ignore_changes` meta-argument only allows static expressions. No references to variables or functions etc. are allowed.

**Comment by stiross79** [comment]
> Would it be possible for you to wrap this module in a local module that handles multiple different cloud-init config files for you?

I will need to check if this is a possibility. But I can see an easy way to do this.

> The `ignore_changes` meta-argument only allows static expressions. No references to variables or functions etc. are allowed.

You are correct. I forgot about that.

**Comment by hknutsen** [comment]
@stiross79 and I had a quick chat.

The conclusion for now is that their requirement to ignore changes to the `custom_data` argument is simply incompatible with this module for now. An option is to not use this module where that requirement is present.

Won't close this issue just yet though, as I'd like to discuss this further and explore other options if possible.

**Comment by helenakallekleiv** [comment]
> @stiross79 and I had a quick chat.
> 
> The conclusion for now is that their requirement to ignore changes to the `custom_data` argument is simply incompatible with this module for now. An option is to not use this module where that requirement is present.
> 
> Won't close this issue just yet though, as I'd like to discuss this further and explore other options if possible.

Based on this discussion, of what I could see when doing a little digging and some clarification from @hknutsen, I believe that this might be as you say, an edge case for the specific project. 

The [example](https://github.com/equinor/terraform-baseline/issues/121#issuecomment-2033992849) presented in this discussion based on a DR scenario, for me, makes adding `ignore_changes` to the `custom_data` argument a no go.

From the quick digging I did, I couldn't see any alternative "pretty" solution to this for now at least 🤷🏼 

Any other thoughts @equinor/terraform-baseline-maintainers?
